### ISSUE TITLE
[Bug] Cron problem

### ISSUE THREAD

**Issue by Edvo1901** [overextended/ox_lib#368]
**Describe the bug**
So there is a bug with the range and lists in the cron. Please have a look the following code for better understanding.

**To Reproduce**
```
-- The code only run at 10:00am and ignore the rest 1,3
lib.cron.new("0,1,3 10 * * *", function()
    print("Cron job running")
end, {debug = true})

-- The code only run at 10:10am once and completely stop. Not trigger every minutes until 30th minutes like in the docs stated
lib.cron.new("10-30 * * * *", function()
    print("Cron job running")
end, {debug = true})
```

**Comment by Edvo1901** [comment]
By the way, I havent tested with hours or day because it taking too long. So not sure if this is only minute bug or everything bug if you know what I mean

**Comment by jag3dagster** [comment]
Likely fixed with 6ab7196. There hasn't been a new release with it yet though. You can try pulling latest source and building to test out the fix.

**Comment by Edvo1901** [comment]
I did but it still doesnt work, it still only run once at 10th minutes then stop, not every minutes until 30th

**Comment by thelindat** [comment]
Leaving this open for now, but the specific issues were fixed while breaking some other stuff (see https://github.com/overextended/ox_lib/issues/384).
Will close both issues once any regressions and underlying issues seem to be resolved.

**Comment by jellyton69** [comment]
This issue started for me 3 days ago after I updated to latest ox_lib, most likely a result of: https://github.com/overextended/ox_lib/commit/45362017c6695afddb04bd64f7152daf2d49cc80

I'll gather some more information about if/when it does run at all once FiveM is back up later.

For those having issues with ox_inventories not saving automatically, this is most likely your issue. I had to put in an event for inventories to save whenever txAdmin notifies about incoming restarts so that it saves at all. Since they don't reliably save on server shutdown.

**Comment by thelindat** [comment]
> I had to put in an event for inventories to save whenever txAdmin notifies about incoming restarts so that it saves at all. Since they don't reliably save on server shutdown.

`txAdmin:events:serverShuttingDown` triggers for both scheduled and manual, and dropping all players triggers a save too. Would be good to hear how this isn't working.

**Comment by jellyton69** [comment]
I'm not too familiar with how txAdmin handles killing fxserver, but from my understanding of the issue with inventory saving, it just seems like the inventory doesn't have time to complete some or all of its update queries before fxserver is killed. I increased shutdownNoticeDelay after I was made aware inventories weren't saving to give oxmysql some time to finish running the queries, but adding the extra events for txAdmin restarts has made that change unnecessary. However, it's also possible that the issue was exacerbated due to ox inventory attempting to save 600-800 inventories on server stop due to cron not running the periodic saves.

**Comment by jellyton69** [comment]
> This issue or some other similar issue? These triggers and all my other test triggers are starting fine.

It looks to be this issue, cron runs the function once on startup and then never again.

**Comment by thelindat** [comment]
Shutdown event is a few seconds or so iirc.

The queries are all sent on the same tick (no await) and use different promise pool connections so they should get sent to the mysql server very quickly - it won't matter if the resource is stopped at that point.

Maybe connections aren't available or there's just too much load for all the queries to get executed in time?

> attempting to save 600-800 inventories on server stop due to cron not running the periodic saves.

I suppose, but I can't get the cronjob to break at this time. The commit you linked resolved issue #384 which they reported solved their issue, but was leading to jobs with negative runtimes passing through and running each tick (resolved by https://github.com/overextended/ox_lib/commit/1a742639493f472024e211a465414b7ba106e21d).

**Comment by jellyton69** [comment]
Looks like the latest commits fixed it, just downloaded the source code and compiled it to test.


Console log as of latest commit:
```
[      script:qb-core] Ticking Hunger and Thirst
[      script:qb-core] (2023/8/6 8:0) ran task 3
[ script:ox_inventory] (2023/8/6 8:0) ran task 3
[      script:qb-core] running task 3 in 299 seconds (4.98 minutes or 0.08 hours)
[ script:ox_inventory] running task 3 in 298 seconds (4.96 minutes or 0.08 hours)
[ script:ox_inventory] (2023/8/6 8:4) ran task 3
[      script:qb-core] Ticking Hunger and Thirst
[      script:qb-core] (2023/8/6 8:5) ran task 3
[ script:ox_inventory] running task 3 in 299 seconds (4.98 minutes or 0.08 hours)
[      script:qb-core] running task 3 in 299 seconds (4.98 minutes or 0.08 hours)
```

Perviously, it would run once, and then print `stopping task`.

**Comment by thelindat** [comment]
> Looks like the latest commits fixed it

uhhhh? what are these tasks you're running?

**Comment by jellyton69** [comment]
This is everything that uses cron:

From qbx-core:
```lua
lib.cron.new(('*/%s * * * *'):format(5), function()
	print("Ticking Hunger and Thirst")
	for src, Player in pairs(QBCore.Players) do
		if Player then
			local newHunger = Player.PlayerData.metadata.hunger - QBCore.Config.Player.HungerRate
			local newThirst = Player.PlayerData.metadata.thirst - QBCore.Config.Player.ThirstRate

			if newHunger <= 0 then
				newHunger = 0
			end
			if newThirst <= 0 then
				newThirst = 0
			end

			Player.Functions.SetMetaData('thirst', newThirst)
			Player.Functions.SetMetaData('hunger', newHunger)

			Player.Functions.Save()
			TriggerClientEvent('hud:client:UpdateNeeds', src, newHunger, newThirst)
		end
	end
end, { debug = true })

lib.cron.new(('*/%s * * * *'):format(45), function()
	print("Running Pay Check")
	for _, Player in pairs(QBCore.Players) do
		if Player then
			local jobName = Player.PlayerData.job.name
			local jobData = QBShared.Jobs[jobName]

			local payment
			if Player.PlayerData.job.grade.level and jobData and jobData.grades and jobData.grades[Player.PlayerData.job.grade.level] then
				payment = jobData.grades[Player.PlayerData.job.grade.level].payment
			end

			if not payment then payment = Player.PlayerData.job.payment or 0 end

			if Player.PlayerData.job and payment > 0 and (jobData.offDutyPay or Player.PlayerData.job.onduty) then
				if QBCore.Config.Money.PaycheckSociety then
					local account = exports['qb-management']:GetAccount(jobName)
					if account ~= 0 then -- Checks if player is employed by a society
						if account < payment then -- Checks if company has enough money to pay society
							TriggerClientEvent('QBCore:Notify', Player.PlayerData.source,
								Lang:t('error.company_too_poor'), 'error')
						else
							Player.Functions.AddMoney('bank', payment, "Paycheck: " .. Player.PlayerData.job.label)
							exports['qb-management']:RemoveMoney(jobName, payment)
							TriggerClientEvent('QBCore:Notify', Player.PlayerData.source,
								Lang:t('info.received_paycheck', { value = payment }))
						end
					else
						Player.Functions.AddMoney('bank', payment, "Paycheck: " .. Player.PlayerData.job.label)
						TriggerClientEvent('QBCore:Notify', Player.PlayerData.source,
							Lang:t('info.received_paycheck', { value = payment }))
					end
				else
					Player.Functions.AddMoney('bank', payment, "Paycheck: " .. Player.PlayerData.job.label)
					TriggerClientEvent('QBCore:Notify', Player.PlayerData.source, Lang:t('info.received_paycheck', { value = payment }))
				end
			end
		end
	end
end, { debug = true })
```

From ox_inventory:
```lua
lib.cron.new('*/5 * * * *', function()
    saveInventories()
end, {debug = true})
```

**Comment by thelindat** [comment]
My ox_inventory cron is obviously the same, and was not stopping - nor did behaviour change when handling steps.

```lua
local function debug(task, date, msg)
    print(('(%s/%s/%s %s:%s) ran task %s - %s'):format(date.year, date.month, date.day, date.hour, date.min, task.id, msg), '\n')
end

lib.cron.new('*/5 * * * *', function(task, date)
    debug(task, date, 'every 5 minutes')
end, { debug = true })
```

The only fix I applied was for tasks running each minute (using `*`, not `*/1`, as they were scheduling for the current minute (thus timing out).

**Comment by jellyton69** [comment]
Alright, I have an update: 

The cron jobs for hunger/thirst and the inventory are functioning normally, however, the one I specified in my last comment that handles paychecks every 45 minutes, stops after its first run.

Console log:
```
[      script:qb-core] (2023/8/7 0:45) ran task 4
[      script:qb-core] stopping task 4 (scheduled time expired 2702 seconds ago)
```

**Comment by thelindat** [comment]
`*/45 * * * *` is a weird cron as you should use a factor of the max value, i.e. factors of 60 for minutes, and the value should run at least twice. So rather than `*/45`, just `45`.

Anyway looks like the check for steps needs an update as it relied on some hacky way to increment tasks that should run on the next hour.

**Comment by thelindat** [comment]
https://github.com/overextended/ox_lib/commit/d268168dc7f723f3afe07105b3b765f6bde2ef2e should resolve the issue with steps.
